### create faculty
POST http://localhost:8080/faculty
Content-Type: application/x-www-form-urlencoded

name = test_name &
color = red

### get by id
GET http://localhost:8080/faculty/1

### update
PUT http://localhost:8080/faculty/4
Content-Type: application/x-www-form-urlencoded

name = 123 &
color = yellow

### create student
POST http://localhost:8080/student/
Content-Type: application/x-www-form-urlencoded

name = Katy &
age = 22

